// Copyright (C) 2023 THALES ALENIA SPACE FRANCE.
// 
// All rights reserved. This program and the accompanying materials
// are made available under the terms of the Eclipse Public License 2.0
// which accompanies this distribution, and is available at
// https://www.eclipse.org/legal/epl-2.0/
// 
// SPDX-License-Identifier: EPL-2.0

// -----------------------------------------------------------------------------
// File Name    : M1.cpp
// Generated by : XsmpSdkGenerator-1.1.0.202308311156
// -----------------------------------------------------------------------------
/// @file Test/M1.cpp

#include "Test/M1.h"

namespace Test {
void M1::DoPublish(::Smp::IPublication *receiver) {
}

void M1::DoConfigure(::Smp::Services::ILogger *logger,
        ::Smp::Services::ILinkRegistry *linkRegistry) {
}

void M1::DoConnect(::Smp::ISimulator *simulator) {
}

void M1::DoDisconnect() {
}

void M1::_ep1() {
    // TODO implement EntryPoint ep1
}
} // namespace Test
