/**
 * *******************************************************************************
 * * Copyright (C) 2020-2022 THALES ALENIA SPACE FRANCE.
 * *
 * * All rights reserved. This program and the accompanying materials
 * * are made available under the terms of the Eclipse Public License 2.0
 * * which accompanies this distribution, and is available at
 * * https://www.eclipse.org/legal/epl-2.0/
 * *
 * * SPDX-License-Identifier: EPL-2.0
 * ******************************************************************************
 */
package org.eclipse.xsmp.smp.xlink;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EDataType;
import org.eclipse.emf.ecore.EEnum;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * <!-- begin-model-doc -->
 * Schema for the W3C XML Linking Language (XLink).
 * 
 * This file is generated by the EGOS-MF XML Schema Generation Tool, version 1.0.3.3.
 * 
 * UML Model Information:
 *     UML model file:  file:/X:/SMPCS/design/uml/gen/xmi/EGOS-MF_XSD_Profile.xmi
 *     UML model name:  EGOS-MF
 *     UML metamodel:   http://schema.omg.org/spec/UML/2.1.1
 *     XMI version:     2.1
 *     XMI exporter:    EGOS-MF XMI Converter (from MagicDraw UML 12.1), version 1.0.3.4
 * 
 * XSLT Processing Information:
 *     Processing date: 2009-03-16T08:47:15.969+01:00
 *     XSLT processor:  SAXON 8.8 from Saxonica
 *     XSLT version:    2.0
 *     XSLT stylesheet: xmi-to-xsd.xslt
 *       
 * <!-- end-model-doc -->
 * @see org.eclipse.xsmp.smp.xlink.XlinkFactory
 * @model kind="package"
 * @generated
 */
public interface XlinkPackage extends EPackage
{
	/**
	 * The package name.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	String eNAME = "xlink";

	/**
	 * The package namespace URI.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	String eNS_URI = "http://www.w3.org/1999/xlink";

	/**
	 * The package namespace name.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	String eNS_PREFIX = "xlink";

	/**
	 * The singleton instance of the package.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	XlinkPackage eINSTANCE = org.eclipse.xsmp.smp.xlink.impl.XlinkPackageImpl.init();

	/**
	 * The meta object id for the '{@link org.eclipse.xsmp.smp.xlink.impl.SimpleLinkBaseImpl <em>Simple Link Base</em>}' class.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @see org.eclipse.xsmp.smp.xlink.impl.SimpleLinkBaseImpl
	 * @see org.eclipse.xsmp.smp.xlink.impl.XlinkPackageImpl#getSimpleLinkBase()
	 * @generated
	 */
	int SIMPLE_LINK_BASE = 0;

	/**
	 * The feature id for the '<em><b>Actuate</b></em>' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int SIMPLE_LINK_BASE__ACTUATE = 0;

	/**
	 * The feature id for the '<em><b>Arcrole</b></em>' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int SIMPLE_LINK_BASE__ARCROLE = 1;

	/**
	 * The feature id for the '<em><b>Role</b></em>' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int SIMPLE_LINK_BASE__ROLE = 2;

	/**
	 * The feature id for the '<em><b>Show</b></em>' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int SIMPLE_LINK_BASE__SHOW = 3;

	/**
	 * The feature id for the '<em><b>Title</b></em>' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int SIMPLE_LINK_BASE__TITLE = 4;

	/**
	 * The feature id for the '<em><b>Link Type</b></em>' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int SIMPLE_LINK_BASE__LINK_TYPE = 5;

	/**
	 * The number of structural features of the '<em>Simple Link Base</em>' class.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int SIMPLE_LINK_BASE_FEATURE_COUNT = 6;

	/**
	 * The meta object id for the '{@link org.eclipse.xsmp.smp.xlink.impl.SimpleLinkImpl <em>Simple Link</em>}' class.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @see org.eclipse.xsmp.smp.xlink.impl.SimpleLinkImpl
	 * @see org.eclipse.xsmp.smp.xlink.impl.XlinkPackageImpl#getSimpleLink()
	 * @generated
	 */
	int SIMPLE_LINK = 1;

	/**
	 * The feature id for the '<em><b>Actuate</b></em>' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int SIMPLE_LINK__ACTUATE = SIMPLE_LINK_BASE__ACTUATE;

	/**
	 * The feature id for the '<em><b>Arcrole</b></em>' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int SIMPLE_LINK__ARCROLE = SIMPLE_LINK_BASE__ARCROLE;

	/**
	 * The feature id for the '<em><b>Role</b></em>' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int SIMPLE_LINK__ROLE = SIMPLE_LINK_BASE__ROLE;

	/**
	 * The feature id for the '<em><b>Show</b></em>' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int SIMPLE_LINK__SHOW = SIMPLE_LINK_BASE__SHOW;

	/**
	 * The feature id for the '<em><b>Title</b></em>' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int SIMPLE_LINK__TITLE = SIMPLE_LINK_BASE__TITLE;

	/**
	 * The feature id for the '<em><b>Link Type</b></em>' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int SIMPLE_LINK__LINK_TYPE = SIMPLE_LINK_BASE__LINK_TYPE;

	/**
	 * The feature id for the '<em><b>Href</b></em>' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int SIMPLE_LINK__HREF = SIMPLE_LINK_BASE_FEATURE_COUNT + 0;

	/**
	 * The number of structural features of the '<em>Simple Link</em>' class.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int SIMPLE_LINK_FEATURE_COUNT = SIMPLE_LINK_BASE_FEATURE_COUNT + 1;

	/**
	 * The meta object id for the '{@link org.eclipse.xsmp.smp.xlink.impl.SimpleLinkRefImpl <em>Simple Link Ref</em>}' class.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @see org.eclipse.xsmp.smp.xlink.impl.SimpleLinkRefImpl
	 * @see org.eclipse.xsmp.smp.xlink.impl.XlinkPackageImpl#getSimpleLinkRef()
	 * @generated
	 */
	int SIMPLE_LINK_REF = 2;

	/**
	 * The feature id for the '<em><b>Actuate</b></em>' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int SIMPLE_LINK_REF__ACTUATE = SIMPLE_LINK_BASE__ACTUATE;

	/**
	 * The feature id for the '<em><b>Arcrole</b></em>' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int SIMPLE_LINK_REF__ARCROLE = SIMPLE_LINK_BASE__ARCROLE;

	/**
	 * The feature id for the '<em><b>Role</b></em>' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int SIMPLE_LINK_REF__ROLE = SIMPLE_LINK_BASE__ROLE;

	/**
	 * The feature id for the '<em><b>Show</b></em>' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int SIMPLE_LINK_REF__SHOW = SIMPLE_LINK_BASE__SHOW;

	/**
	 * The feature id for the '<em><b>Title</b></em>' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int SIMPLE_LINK_REF__TITLE = SIMPLE_LINK_BASE__TITLE;

	/**
	 * The feature id for the '<em><b>Link Type</b></em>' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int SIMPLE_LINK_REF__LINK_TYPE = SIMPLE_LINK_BASE__LINK_TYPE;

	/**
	 * The feature id for the '<em><b>Reference</b></em>' reference.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int SIMPLE_LINK_REF__REFERENCE = SIMPLE_LINK_BASE_FEATURE_COUNT + 0;

	/**
	 * The number of structural features of the '<em>Simple Link Ref</em>' class.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int SIMPLE_LINK_REF_FEATURE_COUNT = SIMPLE_LINK_BASE_FEATURE_COUNT + 1;

	/**
	 * The meta object id for the '{@link org.eclipse.xsmp.smp.xlink.impl.XlinkDocumentImpl <em>Document</em>}' class.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @see org.eclipse.xsmp.smp.xlink.impl.XlinkDocumentImpl
	 * @see org.eclipse.xsmp.smp.xlink.impl.XlinkPackageImpl#getXlinkDocument()
	 * @generated
	 */
	int XLINK_DOCUMENT = 3;

	/**
	 * The feature id for the '<em><b>Mixed</b></em>' attribute list.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int XLINK_DOCUMENT__MIXED = 0;

	/**
	 * The feature id for the '<em><b>XMLNS Prefix Map</b></em>' map.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int XLINK_DOCUMENT__XMLNS_PREFIX_MAP = 1;

	/**
	 * The feature id for the '<em><b>XSI Schema Location</b></em>' map.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int XLINK_DOCUMENT__XSI_SCHEMA_LOCATION = 2;

	/**
	 * The feature id for the '<em><b>Actuate</b></em>' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int XLINK_DOCUMENT__ACTUATE = 3;

	/**
	 * The feature id for the '<em><b>Arcrole</b></em>' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int XLINK_DOCUMENT__ARCROLE = 4;

	/**
	 * The feature id for the '<em><b>From</b></em>' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int XLINK_DOCUMENT__FROM = 5;

	/**
	 * The feature id for the '<em><b>Href</b></em>' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int XLINK_DOCUMENT__HREF = 6;

	/**
	 * The feature id for the '<em><b>Label</b></em>' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int XLINK_DOCUMENT__LABEL = 7;

	/**
	 * The feature id for the '<em><b>Role</b></em>' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int XLINK_DOCUMENT__ROLE = 8;

	/**
	 * The feature id for the '<em><b>Show</b></em>' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int XLINK_DOCUMENT__SHOW = 9;

	/**
	 * The feature id for the '<em><b>Title</b></em>' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int XLINK_DOCUMENT__TITLE = 10;

	/**
	 * The feature id for the '<em><b>To</b></em>' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int XLINK_DOCUMENT__TO = 11;

	/**
	 * The feature id for the '<em><b>Type</b></em>' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int XLINK_DOCUMENT__TYPE = 12;

	/**
	 * The number of structural features of the '<em>Document</em>' class.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int XLINK_DOCUMENT_FEATURE_COUNT = 13;

	/**
	 * The meta object id for the '{@link org.eclipse.xsmp.smp.xlink.ActuateKind <em>Actuate Kind</em>}' enum.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @see org.eclipse.xsmp.smp.xlink.ActuateKind
	 * @see org.eclipse.xsmp.smp.xlink.impl.XlinkPackageImpl#getActuateKind()
	 * @generated
	 */
	int ACTUATE_KIND = 4;

	/**
	 * The meta object id for the '{@link org.eclipse.xsmp.smp.xlink.ShowKind <em>Show Kind</em>}' enum.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @see org.eclipse.xsmp.smp.xlink.ShowKind
	 * @see org.eclipse.xsmp.smp.xlink.impl.XlinkPackageImpl#getShowKind()
	 * @generated
	 */
	int SHOW_KIND = 5;

	/**
	 * The meta object id for the '{@link org.eclipse.xsmp.smp.xlink.TypeKind <em>Type Kind</em>}' enum.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @see org.eclipse.xsmp.smp.xlink.TypeKind
	 * @see org.eclipse.xsmp.smp.xlink.impl.XlinkPackageImpl#getTypeKind()
	 * @generated
	 */
	int TYPE_KIND = 6;

	/**
	 * The meta object id for the '<em>Actuate Kind Object</em>' data type.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @see org.eclipse.xsmp.smp.xlink.ActuateKind
	 * @see org.eclipse.xsmp.smp.xlink.impl.XlinkPackageImpl#getActuateKindObject()
	 * @generated
	 */
	int ACTUATE_KIND_OBJECT = 7;

	/**
	 * The meta object id for the '<em>Show Kind Object</em>' data type.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @see org.eclipse.xsmp.smp.xlink.ShowKind
	 * @see org.eclipse.xsmp.smp.xlink.impl.XlinkPackageImpl#getShowKindObject()
	 * @generated
	 */
	int SHOW_KIND_OBJECT = 8;

	/**
	 * The meta object id for the '<em>Type Kind Object</em>' data type.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @see org.eclipse.xsmp.smp.xlink.TypeKind
	 * @see org.eclipse.xsmp.smp.xlink.impl.XlinkPackageImpl#getTypeKindObject()
	 * @generated
	 */
	int TYPE_KIND_OBJECT = 9;


	/**
	 * Returns the meta object for class '{@link org.eclipse.xsmp.smp.xlink.SimpleLinkBase <em>Simple Link Base</em>}'.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the meta object for class '<em>Simple Link Base</em>'.
	 * @see org.eclipse.xsmp.smp.xlink.SimpleLinkBase
	 * @generated
	 */
	EClass getSimpleLinkBase();

	/**
	 * Returns the meta object for the attribute '{@link org.eclipse.xsmp.smp.xlink.SimpleLinkBase#getActuate <em>Actuate</em>}'.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the meta object for the attribute '<em>Actuate</em>'.
	 * @see org.eclipse.xsmp.smp.xlink.SimpleLinkBase#getActuate()
	 * @see #getSimpleLinkBase()
	 * @generated
	 */
	EAttribute getSimpleLinkBase_Actuate();

	/**
	 * Returns the meta object for the attribute '{@link org.eclipse.xsmp.smp.xlink.SimpleLinkBase#getArcrole <em>Arcrole</em>}'.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the meta object for the attribute '<em>Arcrole</em>'.
	 * @see org.eclipse.xsmp.smp.xlink.SimpleLinkBase#getArcrole()
	 * @see #getSimpleLinkBase()
	 * @generated
	 */
	EAttribute getSimpleLinkBase_Arcrole();

	/**
	 * Returns the meta object for the attribute '{@link org.eclipse.xsmp.smp.xlink.SimpleLinkBase#getRole <em>Role</em>}'.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the meta object for the attribute '<em>Role</em>'.
	 * @see org.eclipse.xsmp.smp.xlink.SimpleLinkBase#getRole()
	 * @see #getSimpleLinkBase()
	 * @generated
	 */
	EAttribute getSimpleLinkBase_Role();

	/**
	 * Returns the meta object for the attribute '{@link org.eclipse.xsmp.smp.xlink.SimpleLinkBase#getShow <em>Show</em>}'.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the meta object for the attribute '<em>Show</em>'.
	 * @see org.eclipse.xsmp.smp.xlink.SimpleLinkBase#getShow()
	 * @see #getSimpleLinkBase()
	 * @generated
	 */
	EAttribute getSimpleLinkBase_Show();

	/**
	 * Returns the meta object for the attribute '{@link org.eclipse.xsmp.smp.xlink.SimpleLinkBase#getTitle <em>Title</em>}'.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the meta object for the attribute '<em>Title</em>'.
	 * @see org.eclipse.xsmp.smp.xlink.SimpleLinkBase#getTitle()
	 * @see #getSimpleLinkBase()
	 * @generated
	 */
	EAttribute getSimpleLinkBase_Title();

	/**
	 * Returns the meta object for the attribute '{@link org.eclipse.xsmp.smp.xlink.SimpleLinkBase#getLinkType <em>Link Type</em>}'.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the meta object for the attribute '<em>Link Type</em>'.
	 * @see org.eclipse.xsmp.smp.xlink.SimpleLinkBase#getLinkType()
	 * @see #getSimpleLinkBase()
	 * @generated
	 */
	EAttribute getSimpleLinkBase_LinkType();

	/**
	 * Returns the meta object for class '{@link org.eclipse.xsmp.smp.xlink.SimpleLink <em>Simple Link</em>}'.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the meta object for class '<em>Simple Link</em>'.
	 * @see org.eclipse.xsmp.smp.xlink.SimpleLink
	 * @generated
	 */
	EClass getSimpleLink();

	/**
	 * Returns the meta object for the attribute '{@link org.eclipse.xsmp.smp.xlink.SimpleLink#getHref <em>Href</em>}'.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the meta object for the attribute '<em>Href</em>'.
	 * @see org.eclipse.xsmp.smp.xlink.SimpleLink#getHref()
	 * @see #getSimpleLink()
	 * @generated
	 */
	EAttribute getSimpleLink_Href();

	/**
	 * Returns the meta object for class '{@link org.eclipse.xsmp.smp.xlink.SimpleLinkRef <em>Simple Link Ref</em>}'.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the meta object for class '<em>Simple Link Ref</em>'.
	 * @see org.eclipse.xsmp.smp.xlink.SimpleLinkRef
	 * @generated
	 */
	EClass getSimpleLinkRef();

	/**
	 * Returns the meta object for the reference '{@link org.eclipse.xsmp.smp.xlink.SimpleLinkRef#getReference <em>Reference</em>}'.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the meta object for the reference '<em>Reference</em>'.
	 * @see org.eclipse.xsmp.smp.xlink.SimpleLinkRef#getReference()
	 * @see #getSimpleLinkRef()
	 * @generated
	 */
	EReference getSimpleLinkRef_Reference();

	/**
	 * Returns the meta object for class '{@link org.eclipse.xsmp.smp.xlink.XlinkDocument <em>Document</em>}'.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the meta object for class '<em>Document</em>'.
	 * @see org.eclipse.xsmp.smp.xlink.XlinkDocument
	 * @generated
	 */
	EClass getXlinkDocument();

	/**
	 * Returns the meta object for the attribute list '{@link org.eclipse.xsmp.smp.xlink.XlinkDocument#getMixed <em>Mixed</em>}'.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the meta object for the attribute list '<em>Mixed</em>'.
	 * @see org.eclipse.xsmp.smp.xlink.XlinkDocument#getMixed()
	 * @see #getXlinkDocument()
	 * @generated
	 */
	EAttribute getXlinkDocument_Mixed();

	/**
	 * Returns the meta object for the map '{@link org.eclipse.xsmp.smp.xlink.XlinkDocument#getXMLNSPrefixMap <em>XMLNS Prefix Map</em>}'.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the meta object for the map '<em>XMLNS Prefix Map</em>'.
	 * @see org.eclipse.xsmp.smp.xlink.XlinkDocument#getXMLNSPrefixMap()
	 * @see #getXlinkDocument()
	 * @generated
	 */
	EReference getXlinkDocument_XMLNSPrefixMap();

	/**
	 * Returns the meta object for the map '{@link org.eclipse.xsmp.smp.xlink.XlinkDocument#getXSISchemaLocation <em>XSI Schema Location</em>}'.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the meta object for the map '<em>XSI Schema Location</em>'.
	 * @see org.eclipse.xsmp.smp.xlink.XlinkDocument#getXSISchemaLocation()
	 * @see #getXlinkDocument()
	 * @generated
	 */
	EReference getXlinkDocument_XSISchemaLocation();

	/**
	 * Returns the meta object for the attribute '{@link org.eclipse.xsmp.smp.xlink.XlinkDocument#getActuate <em>Actuate</em>}'.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the meta object for the attribute '<em>Actuate</em>'.
	 * @see org.eclipse.xsmp.smp.xlink.XlinkDocument#getActuate()
	 * @see #getXlinkDocument()
	 * @generated
	 */
	EAttribute getXlinkDocument_Actuate();

	/**
	 * Returns the meta object for the attribute '{@link org.eclipse.xsmp.smp.xlink.XlinkDocument#getArcrole <em>Arcrole</em>}'.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the meta object for the attribute '<em>Arcrole</em>'.
	 * @see org.eclipse.xsmp.smp.xlink.XlinkDocument#getArcrole()
	 * @see #getXlinkDocument()
	 * @generated
	 */
	EAttribute getXlinkDocument_Arcrole();

	/**
	 * Returns the meta object for the attribute '{@link org.eclipse.xsmp.smp.xlink.XlinkDocument#getFrom <em>From</em>}'.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the meta object for the attribute '<em>From</em>'.
	 * @see org.eclipse.xsmp.smp.xlink.XlinkDocument#getFrom()
	 * @see #getXlinkDocument()
	 * @generated
	 */
	EAttribute getXlinkDocument_From();

	/**
	 * Returns the meta object for the attribute '{@link org.eclipse.xsmp.smp.xlink.XlinkDocument#getHref <em>Href</em>}'.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the meta object for the attribute '<em>Href</em>'.
	 * @see org.eclipse.xsmp.smp.xlink.XlinkDocument#getHref()
	 * @see #getXlinkDocument()
	 * @generated
	 */
	EAttribute getXlinkDocument_Href();

	/**
	 * Returns the meta object for the attribute '{@link org.eclipse.xsmp.smp.xlink.XlinkDocument#getLabel <em>Label</em>}'.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the meta object for the attribute '<em>Label</em>'.
	 * @see org.eclipse.xsmp.smp.xlink.XlinkDocument#getLabel()
	 * @see #getXlinkDocument()
	 * @generated
	 */
	EAttribute getXlinkDocument_Label();

	/**
	 * Returns the meta object for the attribute '{@link org.eclipse.xsmp.smp.xlink.XlinkDocument#getRole <em>Role</em>}'.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the meta object for the attribute '<em>Role</em>'.
	 * @see org.eclipse.xsmp.smp.xlink.XlinkDocument#getRole()
	 * @see #getXlinkDocument()
	 * @generated
	 */
	EAttribute getXlinkDocument_Role();

	/**
	 * Returns the meta object for the attribute '{@link org.eclipse.xsmp.smp.xlink.XlinkDocument#getShow <em>Show</em>}'.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the meta object for the attribute '<em>Show</em>'.
	 * @see org.eclipse.xsmp.smp.xlink.XlinkDocument#getShow()
	 * @see #getXlinkDocument()
	 * @generated
	 */
	EAttribute getXlinkDocument_Show();

	/**
	 * Returns the meta object for the attribute '{@link org.eclipse.xsmp.smp.xlink.XlinkDocument#getTitle <em>Title</em>}'.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the meta object for the attribute '<em>Title</em>'.
	 * @see org.eclipse.xsmp.smp.xlink.XlinkDocument#getTitle()
	 * @see #getXlinkDocument()
	 * @generated
	 */
	EAttribute getXlinkDocument_Title();

	/**
	 * Returns the meta object for the attribute '{@link org.eclipse.xsmp.smp.xlink.XlinkDocument#getTo <em>To</em>}'.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the meta object for the attribute '<em>To</em>'.
	 * @see org.eclipse.xsmp.smp.xlink.XlinkDocument#getTo()
	 * @see #getXlinkDocument()
	 * @generated
	 */
	EAttribute getXlinkDocument_To();

	/**
	 * Returns the meta object for the attribute '{@link org.eclipse.xsmp.smp.xlink.XlinkDocument#getType <em>Type</em>}'.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the meta object for the attribute '<em>Type</em>'.
	 * @see org.eclipse.xsmp.smp.xlink.XlinkDocument#getType()
	 * @see #getXlinkDocument()
	 * @generated
	 */
	EAttribute getXlinkDocument_Type();

	/**
	 * Returns the meta object for enum '{@link org.eclipse.xsmp.smp.xlink.ActuateKind <em>Actuate Kind</em>}'.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the meta object for enum '<em>Actuate Kind</em>'.
	 * @see org.eclipse.xsmp.smp.xlink.ActuateKind
	 * @generated
	 */
	EEnum getActuateKind();

	/**
	 * Returns the meta object for enum '{@link org.eclipse.xsmp.smp.xlink.ShowKind <em>Show Kind</em>}'.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the meta object for enum '<em>Show Kind</em>'.
	 * @see org.eclipse.xsmp.smp.xlink.ShowKind
	 * @generated
	 */
	EEnum getShowKind();

	/**
	 * Returns the meta object for enum '{@link org.eclipse.xsmp.smp.xlink.TypeKind <em>Type Kind</em>}'.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the meta object for enum '<em>Type Kind</em>'.
	 * @see org.eclipse.xsmp.smp.xlink.TypeKind
	 * @generated
	 */
	EEnum getTypeKind();

	/**
	 * Returns the meta object for data type '{@link org.eclipse.xsmp.smp.xlink.ActuateKind <em>Actuate Kind Object</em>}'.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the meta object for data type '<em>Actuate Kind Object</em>'.
	 * @see org.eclipse.xsmp.smp.xlink.ActuateKind
	 * @model instanceClass="org.eclipse.xsmp.smp.xlink.ActuateKind"
	 *        extendedMetaData="name='ActuateKind:Object' baseType='ActuateKind'"
	 * @generated
	 */
	EDataType getActuateKindObject();

	/**
	 * Returns the meta object for data type '{@link org.eclipse.xsmp.smp.xlink.ShowKind <em>Show Kind Object</em>}'.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the meta object for data type '<em>Show Kind Object</em>'.
	 * @see org.eclipse.xsmp.smp.xlink.ShowKind
	 * @model instanceClass="org.eclipse.xsmp.smp.xlink.ShowKind"
	 *        extendedMetaData="name='ShowKind:Object' baseType='ShowKind'"
	 * @generated
	 */
	EDataType getShowKindObject();

	/**
	 * Returns the meta object for data type '{@link org.eclipse.xsmp.smp.xlink.TypeKind <em>Type Kind Object</em>}'.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the meta object for data type '<em>Type Kind Object</em>'.
	 * @see org.eclipse.xsmp.smp.xlink.TypeKind
	 * @model instanceClass="org.eclipse.xsmp.smp.xlink.TypeKind"
	 *        extendedMetaData="name='TypeKind:Object' baseType='TypeKind'"
	 * @generated
	 */
	EDataType getTypeKindObject();

	/**
	 * Returns the factory that creates the instances of the model.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the factory that creates the instances of the model.
	 * @generated
	 */
	XlinkFactory getXlinkFactory();

	/**
	 * <!-- begin-user-doc -->
	 * Defines literals for the meta objects that represent
	 * <ul>
	 *   <li>each class,</li>
	 *   <li>each feature of each class,</li>
	 *   <li>each enum,</li>
	 *   <li>and each data type</li>
	 * </ul>
	 * <!-- end-user-doc -->
	 * @generated
	 */
	interface Literals
	{
		/**
		 * The meta object literal for the '{@link org.eclipse.xsmp.smp.xlink.impl.SimpleLinkBaseImpl <em>Simple Link Base</em>}' class.
		 * <!-- begin-user-doc -->
		 * <!-- end-user-doc -->
		 * @see org.eclipse.xsmp.smp.xlink.impl.SimpleLinkBaseImpl
		 * @see org.eclipse.xsmp.smp.xlink.impl.XlinkPackageImpl#getSimpleLinkBase()
		 * @generated
		 */
		EClass SIMPLE_LINK_BASE = eINSTANCE.getSimpleLinkBase();

		/**
		 * The meta object literal for the '<em><b>Actuate</b></em>' attribute feature.
		 * <!-- begin-user-doc -->
		 * <!-- end-user-doc -->
		 * @generated
		 */
		EAttribute SIMPLE_LINK_BASE__ACTUATE = eINSTANCE.getSimpleLinkBase_Actuate();

		/**
		 * The meta object literal for the '<em><b>Arcrole</b></em>' attribute feature.
		 * <!-- begin-user-doc -->
		 * <!-- end-user-doc -->
		 * @generated
		 */
		EAttribute SIMPLE_LINK_BASE__ARCROLE = eINSTANCE.getSimpleLinkBase_Arcrole();

		/**
		 * The meta object literal for the '<em><b>Role</b></em>' attribute feature.
		 * <!-- begin-user-doc -->
		 * <!-- end-user-doc -->
		 * @generated
		 */
		EAttribute SIMPLE_LINK_BASE__ROLE = eINSTANCE.getSimpleLinkBase_Role();

		/**
		 * The meta object literal for the '<em><b>Show</b></em>' attribute feature.
		 * <!-- begin-user-doc -->
		 * <!-- end-user-doc -->
		 * @generated
		 */
		EAttribute SIMPLE_LINK_BASE__SHOW = eINSTANCE.getSimpleLinkBase_Show();

		/**
		 * The meta object literal for the '<em><b>Title</b></em>' attribute feature.
		 * <!-- begin-user-doc -->
		 * <!-- end-user-doc -->
		 * @generated
		 */
		EAttribute SIMPLE_LINK_BASE__TITLE = eINSTANCE.getSimpleLinkBase_Title();

		/**
		 * The meta object literal for the '<em><b>Link Type</b></em>' attribute feature.
		 * <!-- begin-user-doc -->
		 * <!-- end-user-doc -->
		 * @generated
		 */
		EAttribute SIMPLE_LINK_BASE__LINK_TYPE = eINSTANCE.getSimpleLinkBase_LinkType();

		/**
		 * The meta object literal for the '{@link org.eclipse.xsmp.smp.xlink.impl.SimpleLinkImpl <em>Simple Link</em>}' class.
		 * <!-- begin-user-doc -->
		 * <!-- end-user-doc -->
		 * @see org.eclipse.xsmp.smp.xlink.impl.SimpleLinkImpl
		 * @see org.eclipse.xsmp.smp.xlink.impl.XlinkPackageImpl#getSimpleLink()
		 * @generated
		 */
		EClass SIMPLE_LINK = eINSTANCE.getSimpleLink();

		/**
		 * The meta object literal for the '<em><b>Href</b></em>' attribute feature.
		 * <!-- begin-user-doc -->
		 * <!-- end-user-doc -->
		 * @generated
		 */
		EAttribute SIMPLE_LINK__HREF = eINSTANCE.getSimpleLink_Href();

		/**
		 * The meta object literal for the '{@link org.eclipse.xsmp.smp.xlink.impl.SimpleLinkRefImpl <em>Simple Link Ref</em>}' class.
		 * <!-- begin-user-doc -->
		 * <!-- end-user-doc -->
		 * @see org.eclipse.xsmp.smp.xlink.impl.SimpleLinkRefImpl
		 * @see org.eclipse.xsmp.smp.xlink.impl.XlinkPackageImpl#getSimpleLinkRef()
		 * @generated
		 */
		EClass SIMPLE_LINK_REF = eINSTANCE.getSimpleLinkRef();

		/**
		 * The meta object literal for the '<em><b>Reference</b></em>' reference feature.
		 * <!-- begin-user-doc -->
		 * <!-- end-user-doc -->
		 * @generated
		 */
		EReference SIMPLE_LINK_REF__REFERENCE = eINSTANCE.getSimpleLinkRef_Reference();

		/**
		 * The meta object literal for the '{@link org.eclipse.xsmp.smp.xlink.impl.XlinkDocumentImpl <em>Document</em>}' class.
		 * <!-- begin-user-doc -->
		 * <!-- end-user-doc -->
		 * @see org.eclipse.xsmp.smp.xlink.impl.XlinkDocumentImpl
		 * @see org.eclipse.xsmp.smp.xlink.impl.XlinkPackageImpl#getXlinkDocument()
		 * @generated
		 */
		EClass XLINK_DOCUMENT = eINSTANCE.getXlinkDocument();

		/**
		 * The meta object literal for the '<em><b>Mixed</b></em>' attribute list feature.
		 * <!-- begin-user-doc -->
		 * <!-- end-user-doc -->
		 * @generated
		 */
		EAttribute XLINK_DOCUMENT__MIXED = eINSTANCE.getXlinkDocument_Mixed();

		/**
		 * The meta object literal for the '<em><b>XMLNS Prefix Map</b></em>' map feature.
		 * <!-- begin-user-doc -->
		 * <!-- end-user-doc -->
		 * @generated
		 */
		EReference XLINK_DOCUMENT__XMLNS_PREFIX_MAP = eINSTANCE.getXlinkDocument_XMLNSPrefixMap();

		/**
		 * The meta object literal for the '<em><b>XSI Schema Location</b></em>' map feature.
		 * <!-- begin-user-doc -->
		 * <!-- end-user-doc -->
		 * @generated
		 */
		EReference XLINK_DOCUMENT__XSI_SCHEMA_LOCATION = eINSTANCE.getXlinkDocument_XSISchemaLocation();

		/**
		 * The meta object literal for the '<em><b>Actuate</b></em>' attribute feature.
		 * <!-- begin-user-doc -->
		 * <!-- end-user-doc -->
		 * @generated
		 */
		EAttribute XLINK_DOCUMENT__ACTUATE = eINSTANCE.getXlinkDocument_Actuate();

		/**
		 * The meta object literal for the '<em><b>Arcrole</b></em>' attribute feature.
		 * <!-- begin-user-doc -->
		 * <!-- end-user-doc -->
		 * @generated
		 */
		EAttribute XLINK_DOCUMENT__ARCROLE = eINSTANCE.getXlinkDocument_Arcrole();

		/**
		 * The meta object literal for the '<em><b>From</b></em>' attribute feature.
		 * <!-- begin-user-doc -->
		 * <!-- end-user-doc -->
		 * @generated
		 */
		EAttribute XLINK_DOCUMENT__FROM = eINSTANCE.getXlinkDocument_From();

		/**
		 * The meta object literal for the '<em><b>Href</b></em>' attribute feature.
		 * <!-- begin-user-doc -->
		 * <!-- end-user-doc -->
		 * @generated
		 */
		EAttribute XLINK_DOCUMENT__HREF = eINSTANCE.getXlinkDocument_Href();

		/**
		 * The meta object literal for the '<em><b>Label</b></em>' attribute feature.
		 * <!-- begin-user-doc -->
		 * <!-- end-user-doc -->
		 * @generated
		 */
		EAttribute XLINK_DOCUMENT__LABEL = eINSTANCE.getXlinkDocument_Label();

		/**
		 * The meta object literal for the '<em><b>Role</b></em>' attribute feature.
		 * <!-- begin-user-doc -->
		 * <!-- end-user-doc -->
		 * @generated
		 */
		EAttribute XLINK_DOCUMENT__ROLE = eINSTANCE.getXlinkDocument_Role();

		/**
		 * The meta object literal for the '<em><b>Show</b></em>' attribute feature.
		 * <!-- begin-user-doc -->
		 * <!-- end-user-doc -->
		 * @generated
		 */
		EAttribute XLINK_DOCUMENT__SHOW = eINSTANCE.getXlinkDocument_Show();

		/**
		 * The meta object literal for the '<em><b>Title</b></em>' attribute feature.
		 * <!-- begin-user-doc -->
		 * <!-- end-user-doc -->
		 * @generated
		 */
		EAttribute XLINK_DOCUMENT__TITLE = eINSTANCE.getXlinkDocument_Title();

		/**
		 * The meta object literal for the '<em><b>To</b></em>' attribute feature.
		 * <!-- begin-user-doc -->
		 * <!-- end-user-doc -->
		 * @generated
		 */
		EAttribute XLINK_DOCUMENT__TO = eINSTANCE.getXlinkDocument_To();

		/**
		 * The meta object literal for the '<em><b>Type</b></em>' attribute feature.
		 * <!-- begin-user-doc -->
		 * <!-- end-user-doc -->
		 * @generated
		 */
		EAttribute XLINK_DOCUMENT__TYPE = eINSTANCE.getXlinkDocument_Type();

		/**
		 * The meta object literal for the '{@link org.eclipse.xsmp.smp.xlink.ActuateKind <em>Actuate Kind</em>}' enum.
		 * <!-- begin-user-doc -->
		 * <!-- end-user-doc -->
		 * @see org.eclipse.xsmp.smp.xlink.ActuateKind
		 * @see org.eclipse.xsmp.smp.xlink.impl.XlinkPackageImpl#getActuateKind()
		 * @generated
		 */
		EEnum ACTUATE_KIND = eINSTANCE.getActuateKind();

		/**
		 * The meta object literal for the '{@link org.eclipse.xsmp.smp.xlink.ShowKind <em>Show Kind</em>}' enum.
		 * <!-- begin-user-doc -->
		 * <!-- end-user-doc -->
		 * @see org.eclipse.xsmp.smp.xlink.ShowKind
		 * @see org.eclipse.xsmp.smp.xlink.impl.XlinkPackageImpl#getShowKind()
		 * @generated
		 */
		EEnum SHOW_KIND = eINSTANCE.getShowKind();

		/**
		 * The meta object literal for the '{@link org.eclipse.xsmp.smp.xlink.TypeKind <em>Type Kind</em>}' enum.
		 * <!-- begin-user-doc -->
		 * <!-- end-user-doc -->
		 * @see org.eclipse.xsmp.smp.xlink.TypeKind
		 * @see org.eclipse.xsmp.smp.xlink.impl.XlinkPackageImpl#getTypeKind()
		 * @generated
		 */
		EEnum TYPE_KIND = eINSTANCE.getTypeKind();

		/**
		 * The meta object literal for the '<em>Actuate Kind Object</em>' data type.
		 * <!-- begin-user-doc -->
		 * <!-- end-user-doc -->
		 * @see org.eclipse.xsmp.smp.xlink.ActuateKind
		 * @see org.eclipse.xsmp.smp.xlink.impl.XlinkPackageImpl#getActuateKindObject()
		 * @generated
		 */
		EDataType ACTUATE_KIND_OBJECT = eINSTANCE.getActuateKindObject();

		/**
		 * The meta object literal for the '<em>Show Kind Object</em>' data type.
		 * <!-- begin-user-doc -->
		 * <!-- end-user-doc -->
		 * @see org.eclipse.xsmp.smp.xlink.ShowKind
		 * @see org.eclipse.xsmp.smp.xlink.impl.XlinkPackageImpl#getShowKindObject()
		 * @generated
		 */
		EDataType SHOW_KIND_OBJECT = eINSTANCE.getShowKindObject();

		/**
		 * The meta object literal for the '<em>Type Kind Object</em>' data type.
		 * <!-- begin-user-doc -->
		 * <!-- end-user-doc -->
		 * @see org.eclipse.xsmp.smp.xlink.TypeKind
		 * @see org.eclipse.xsmp.smp.xlink.impl.XlinkPackageImpl#getTypeKindObject()
		 * @generated
		 */
		EDataType TYPE_KIND_OBJECT = eINSTANCE.getTypeKindObject();

	}

} //XlinkPackage
