# Copyright (C) 2023 THALES ALENIA SPACE FRANCE.
# 
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Eclipse Public License 2.0
# which accompanies this distribution, and is available at
# https://www.eclipse.org/legal/epl-2.0/
# 
# SPDX-License-Identifier: EPL-2.0

# -----------------------------------------------------------------------------
# File Name 	: xsmp_sdk_tests.py
# Generated by 	: PythonGenerator
# -----------------------------------------------------------------------------
# This file is auto-generated. Do not edit otherwise your changes will be lost.

import ecss_smp_smp
import types


class Test(types.ModuleType):
    class M1(ecss_smp_smp.Smp.IModel):
        uuid:ecss_smp_smp.Smp.Uuid = ecss_smp_smp.Smp.Uuid("8fb0a345-9658-466d-afff-b63de8c29e01")
        package_name:str = __name__
    
    
    pass

