/**
 * *******************************************************************************
 * * Copyright (C) 2020-2022 THALES ALENIA SPACE FRANCE.
 * *
 * * All rights reserved. This program and the accompanying materials
 * * are made available under the terms of the Eclipse Public License 2.0
 * * which accompanies this distribution, and is available at
 * * https://www.eclipse.org/legal/epl-2.0/
 * *
 * * SPDX-License-Identifier: EPL-2.0
 * ******************************************************************************
 */
package org.eclipse.xsmp.smp.smdl.configuration;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

import org.eclipse.xsmp.smp.core.elements.ElementsPackage;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * <!-- begin-model-doc -->
 * This schema defines all metamodel elements that are needed in order to define an SMDL configuration document. A configuration document allows specifying arbitrary field values of component instances in the simulation hierarchy. This can be used to initialise or reinitialise the simulation.
 * 
 * This file is generated by the UMF XML Schema Generation Tool, version 2.1.0.qualifier.
 * 
 * UML Model Information:
 *     UML model file:  file:/C:/Data/Projects/ECSS16/Software/Windows/pfritzen/SMP/Src/ecss.smp.smdl/target/xmi/ecss.smp.smdl.xmi
 *     UML model name:  Obsolete
 *     UML metamodel:   http://schema.omg.org/spec/UML/2.2
 *     XMI version:     2.1
 *     XMI exporter:    UMF XMI Converter (from MagicDraw UML 17.0.2), version 2.1.0.qualifier
 * 
 * XSLT Processing Information:
 *     Processing date: 2019-10-28T17:05:22.729+01:00
 *     XSLT processor:  SAXON 8.8.0.7 from Saxonica
 *     XSLT version:    2.0
 *     XSLT stylesheet: xmi-to-xsd.xslt
 *       
 * This schema provides basic types and typing mechanisms, together with appropriate value specification mechanisms.
 * 
 * This file is generated by the UMF XML Schema Generation Tool, version 2.1.0.qualifier.
 * 
 * UML Model Information:
 *     UML model file:  file:/C:/Data/Projects/ECSS16/Software/Windows/pfritzen/SMP/Src/ecss.smp.smdl/target/xmi/ecss.smp.core.xmi
 *     UML model name:  Obsolete
 *     UML metamodel:   http://schema.omg.org/spec/UML/2.2
 *     XMI version:     2.1
 *     XMI exporter:    UMF XMI Converter (from MagicDraw UML 17.0.2), version 2.1.0.qualifier
 * 
 * XSLT Processing Information:
 *     Processing date: 2019-10-28T16:29:39.084+01:00
 *     XSLT processor:  SAXON 8.8.0.7 from Saxonica
 *     XSLT version:    2.0
 *     XSLT stylesheet: xmi-to-xsd.xslt
 *       
 * This schema defines base metaclasses and annotation mechanisms used throughout the SMP Metamodel.
 * 
 * This file is generated by the UMF XML Schema Generation Tool, version 2.1.0.qualifier.
 * 
 * UML Model Information:
 *     UML model file:  file:/C:/Data/Projects/ECSS16/Software/Windows/pfritzen/SMP/Src/ecss.smp.smdl/target/xmi/ecss.smp.core.xmi
 *     UML model name:  Obsolete
 *     UML metamodel:   http://schema.omg.org/spec/UML/2.2
 *     XMI version:     2.1
 *     XMI exporter:    UMF XMI Converter (from MagicDraw UML 17.0.2), version 2.1.0.qualifier
 * 
 * XSLT Processing Information:
 *     Processing date: 2019-10-28T16:29:39.084+01:00
 *     XSLT processor:  SAXON 8.8.0.7 from Saxonica
 *     XSLT version:    2.0
 *     XSLT stylesheet: xmi-to-xsd.xslt
 *       
 * 
 *       This schema document provides attribute declarations and attribute group, complex type and simple type definitions which can be used in the construction of user schemas to define the structure of particular linking constructs, e.g.
 *       < xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:xl="http://www.w3.org/1999/xlink"> <xs:import namespace="http://www.w3.org/1999/xlink" location="http://www.w3.org/1999/xlink.xsd"> <xs:element name="mySimple"> <xs:complexType> ... <xs:attributeGroup ref="xl:simpleAttrs"/> ... </xs:complexType> </xs:element> ...< /xs:schema>
 *     
 * 
 *      
 *   <div xmlns="http://www.w3.org/1999/xhtml">
 *         
 *     <h1>About the XML namespace</h1>
 *         
 *     <div class="bodytext">
 *            
 *       <p>
 *       This schema document describes the XML namespace, in a form
 *       suitable for import by other schema documents.
 *      </p>
 *            
 *       <p>
 *               See 
 *         <a href="http://www.w3.org/XML/1998/namespace.html">
 *       http://www.w3.org/XML/1998/namespace.html</a>
 *          and
 *       
 *         <a href="http://www.w3.org/TR/REC-xml">
 *       http://www.w3.org/TR/REC-xml</a>
 *          for information 
 *       about this namespace.
 *      
 *       </p>
 *            
 *       <p>
 *       Note that local names in this namespace are intended to be
 *       defined only by the World Wide Web Consortium or its subgroups.
 *       The names currently defined in this namespace are listed below.
 *       They should not be used with conflicting semantics by any Working
 *       Group, specification, or document instance.
 *      </p>
 *            
 *       <p>
 *            
 *       See further below in this document for more information about 
 *         <a href="#usage">how to refer to this schema document from your own
 *       XSD schema documents</a>
 *          and about 
 *         <a href="#nsversioning">the
 *       namespace-versioning policy governing this schema document</a>
 *         .
 *      
 *       </p>
 *           
 *     </div>
 *        
 *   </div>
 *     
 * 
 * 
 *      
 *   <div xmlns="http://www.w3.org/1999/xhtml">
 *        
 *     
 *     <h3>Father (in any context at all)</h3>
 *      
 * 
 *     
 *     <div class="bodytext">
 *            
 *       <p>
 *       denotes Jon Bosak, the chair of 
 *       the original XML Working Group.  This name is reserved by 
 *       the following decision of the W3C XML Plenary and 
 *       XML Coordination groups:
 *      </p>
 *            
 *       <blockquote>
 *                
 *         <p>
 * 	In appreciation for his vision, leadership and
 * 	dedication the W3C XML Plenary on this 10th day of
 * 	February, 2000, reserves for Jon Bosak in perpetuity
 * 	the XML name "xml:Father".
 *        </p>
 *              
 *       </blockquote>
 *           
 *     </div>
 *        
 *   </div>
 *     
 * 
 * 
 *      
 *   <div id="usage" xml:id="usage" xmlns="http://www.w3.org/1999/xhtml">
 *         
 *     <h2>
 *       <a name="usage">About this schema document</a>
 *     </h2>
 *         
 *     <div class="bodytext">
 *            
 *       <p>
 *               This schema defines attributes and an attribute group suitable
 *       for use by schemas wishing to allow 
 *         <code>xml:base</code>
 *         ,
 *       
 *         <code>xml:lang</code>
 *         , 
 *         <code>xml:space</code>
 *          or
 *       
 *         <code>xml:id</code>
 *          attributes on elements they define.
 *      
 *       </p>
 *            
 *       <p>
 *       To enable this, such a schema must import this schema for
 *       the XML namespace, e.g. as follows:
 *      </p>
 *            
 *       <pre>
 *           &lt;schema . . .&gt;
 *            . . .
 *            &lt;import namespace="http://www.w3.org/XML/1998/namespace"
 *                       schemaLocation="http://www.w3.org/2001/xml.xsd"/&gt;
 *      </pre>
 *            
 *       <p>
 *       or
 *      </p>
 *            
 *       <pre>
 *            &lt;import namespace="http://www.w3.org/XML/1998/namespace"
 *                       schemaLocation="http://www.w3.org/2009/01/xml.xsd"/&gt;
 *      </pre>
 *            
 *       <p>
 *       Subsequently, qualified reference to any of the attributes or the
 *       group defined below will have the desired effect, e.g.
 *      </p>
 *            
 *       <pre>
 *           &lt;type . . .&gt;
 *            . . .
 *            &lt;attributeGroup ref="xml:specialAttrs"/&gt;
 *      </pre>
 *            
 *       <p>
 *       will define a type which will schema-validate an instance element
 *       with any of those attributes.
 *      </p>
 *           
 *     </div>
 *        
 *   </div>
 *     
 * 
 * 
 *      
 *   <div id="nsversioning" xml:id="nsversioning" xmlns="http://www.w3.org/1999/xhtml">
 *         
 *     <h2>
 *       <a name="nsversioning">Versioning policy for this schema document</a>
 *     </h2>
 *         
 *     <div class="bodytext">
 *            
 *       <p>
 *               In keeping with the XML Schema WG's standard versioning
 *       policy, this schema document will persist at
 *       
 *         <a href="http://www.w3.org/2009/01/xml.xsd">
 *        http://www.w3.org/2009/01/xml.xsd</a>
 *         .
 *      
 *       </p>
 *            
 *       <p>
 *               At the date of issue it can also be found at
 *       
 *         <a href="http://www.w3.org/2001/xml.xsd">
 *        http://www.w3.org/2001/xml.xsd</a>
 *         .
 *      
 *       </p>
 *            
 *       <p>
 *               The schema document at that URI may however change in the future,
 *       in order to remain compatible with the latest version of XML
 *       Schema itself, or with the XML namespace itself.  In other words,
 *       if the XML Schema or XML namespaces change, the version of this
 *       document at 
 *         <a href="http://www.w3.org/2001/xml.xsd">
 *        http://www.w3.org/2001/xml.xsd 
 *       </a>
 *          
 *       will change accordingly; the version at 
 *       
 *         <a href="http://www.w3.org/2009/01/xml.xsd">
 *        http://www.w3.org/2009/01/xml.xsd 
 *       </a>
 *          
 *       will not change.
 *      
 *       </p>
 *            
 *       <p>
 *       Previous dated (and unchanging) versions of this schema 
 *       document are at:
 *      </p>
 *            
 *       <ul>
 *               
 *         <li>
 *           <a href="http://www.w3.org/2009/01/xml.xsd">
 * 	http://www.w3.org/2009/01/xml.xsd</a>
 *         </li>
 *               
 *         <li>
 *           <a href="http://www.w3.org/2007/08/xml.xsd">
 * 	http://www.w3.org/2007/08/xml.xsd</a>
 *         </li>
 *               
 *         <li>
 *           <a href="http://www.w3.org/2004/10/xml.xsd">
 * 	http://www.w3.org/2004/10/xml.xsd</a>
 *         </li>
 *               
 *         <li>
 *           <a href="http://www.w3.org/2001/03/xml.xsd">
 * 	http://www.w3.org/2001/03/xml.xsd</a>
 *         </li>
 *              
 *       </ul>
 *           
 *     </div>
 *        
 *   </div>
 *     
 * 
 * <!-- end-model-doc -->
 * @see org.eclipse.xsmp.smp.smdl.configuration.ConfigurationFactory
 * @model kind="package"
 * @generated
 */
public interface ConfigurationPackage extends EPackage
{
	/**
	 * The package name.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	String eNAME = "configuration";

	/**
	 * The package namespace URI.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	String eNS_URI = "http://www.ecss.nl/smp/2019/Smdl/Configuration";

	/**
	 * The package namespace name.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	String eNS_PREFIX = "Configuration";

	/**
	 * The package content type ID.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	String eCONTENT_TYPE = "org.opensmp.smdl.smpcfg";

	/**
	 * The singleton instance of the package.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	ConfigurationPackage eINSTANCE = org.eclipse.xsmp.smp.smdl.configuration.impl.ConfigurationPackageImpl.init();

	/**
	 * The meta object id for the '{@link org.eclipse.xsmp.smp.smdl.configuration.impl.ComponentConfigurationImpl <em>Component Configuration</em>}' class.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @see org.eclipse.xsmp.smp.smdl.configuration.impl.ComponentConfigurationImpl
	 * @see org.eclipse.xsmp.smp.smdl.configuration.impl.ConfigurationPackageImpl#getComponentConfiguration()
	 * @generated
	 */
	int COMPONENT_CONFIGURATION = 0;

	/**
	 * The feature id for the '<em><b>Include</b></em>' containment reference list.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int COMPONENT_CONFIGURATION__INCLUDE = 0;

	/**
	 * The feature id for the '<em><b>Component</b></em>' containment reference list.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int COMPONENT_CONFIGURATION__COMPONENT = 1;

	/**
	 * The feature id for the '<em><b>Field Value</b></em>' containment reference list.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int COMPONENT_CONFIGURATION__FIELD_VALUE = 2;

	/**
	 * The feature id for the '<em><b>Path</b></em>' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int COMPONENT_CONFIGURATION__PATH = 3;

	/**
	 * The number of structural features of the '<em>Component Configuration</em>' class.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int COMPONENT_CONFIGURATION_FEATURE_COUNT = 4;

	/**
	 * The meta object id for the '{@link org.eclipse.xsmp.smp.smdl.configuration.impl.ConfigurationImpl <em>Configuration</em>}' class.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @see org.eclipse.xsmp.smp.smdl.configuration.impl.ConfigurationImpl
	 * @see org.eclipse.xsmp.smp.smdl.configuration.impl.ConfigurationPackageImpl#getConfiguration()
	 * @generated
	 */
	int CONFIGURATION = 1;

	/**
	 * The feature id for the '<em><b>Description</b></em>' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int CONFIGURATION__DESCRIPTION = ElementsPackage.DOCUMENT__DESCRIPTION;

	/**
	 * The feature id for the '<em><b>Metadata</b></em>' containment reference list.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int CONFIGURATION__METADATA = ElementsPackage.DOCUMENT__METADATA;

	/**
	 * The feature id for the '<em><b>Id</b></em>' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int CONFIGURATION__ID = ElementsPackage.DOCUMENT__ID;

	/**
	 * The feature id for the '<em><b>Name</b></em>' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int CONFIGURATION__NAME = ElementsPackage.DOCUMENT__NAME;

	/**
	 * The feature id for the '<em><b>Title</b></em>' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int CONFIGURATION__TITLE = ElementsPackage.DOCUMENT__TITLE;

	/**
	 * The feature id for the '<em><b>Date</b></em>' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int CONFIGURATION__DATE = ElementsPackage.DOCUMENT__DATE;

	/**
	 * The feature id for the '<em><b>Creator</b></em>' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int CONFIGURATION__CREATOR = ElementsPackage.DOCUMENT__CREATOR;

	/**
	 * The feature id for the '<em><b>Version</b></em>' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int CONFIGURATION__VERSION = ElementsPackage.DOCUMENT__VERSION;

	/**
	 * The feature id for the '<em><b>Include</b></em>' containment reference list.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int CONFIGURATION__INCLUDE = ElementsPackage.DOCUMENT_FEATURE_COUNT + 0;

	/**
	 * The feature id for the '<em><b>Component</b></em>' containment reference list.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int CONFIGURATION__COMPONENT = ElementsPackage.DOCUMENT_FEATURE_COUNT + 1;

	/**
	 * The number of structural features of the '<em>Configuration</em>' class.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int CONFIGURATION_FEATURE_COUNT = ElementsPackage.DOCUMENT_FEATURE_COUNT + 2;

	/**
	 * The meta object id for the '{@link org.eclipse.xsmp.smp.smdl.configuration.impl.ConfigurationDocumentRootImpl <em>Document Root</em>}' class.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @see org.eclipse.xsmp.smp.smdl.configuration.impl.ConfigurationDocumentRootImpl
	 * @see org.eclipse.xsmp.smp.smdl.configuration.impl.ConfigurationPackageImpl#getConfigurationDocumentRoot()
	 * @generated
	 */
	int CONFIGURATION_DOCUMENT_ROOT = 2;

	/**
	 * The feature id for the '<em><b>Mixed</b></em>' attribute list.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int CONFIGURATION_DOCUMENT_ROOT__MIXED = 0;

	/**
	 * The feature id for the '<em><b>XMLNS Prefix Map</b></em>' map.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int CONFIGURATION_DOCUMENT_ROOT__XMLNS_PREFIX_MAP = 1;

	/**
	 * The feature id for the '<em><b>XSI Schema Location</b></em>' map.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int CONFIGURATION_DOCUMENT_ROOT__XSI_SCHEMA_LOCATION = 2;

	/**
	 * The feature id for the '<em><b>Configuration</b></em>' containment reference.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int CONFIGURATION_DOCUMENT_ROOT__CONFIGURATION = 3;

	/**
	 * The number of structural features of the '<em>Document Root</em>' class.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int CONFIGURATION_DOCUMENT_ROOT_FEATURE_COUNT = 4;

	/**
	 * The meta object id for the '{@link org.eclipse.xsmp.smp.smdl.configuration.impl.ConfigurationOfConfigurationUsageImpl <em>Of Configuration Usage</em>}' class.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @see org.eclipse.xsmp.smp.smdl.configuration.impl.ConfigurationOfConfigurationUsageImpl
	 * @see org.eclipse.xsmp.smp.smdl.configuration.impl.ConfigurationPackageImpl#getConfigurationOfConfigurationUsage()
	 * @generated
	 */
	int CONFIGURATION_OF_CONFIGURATION_USAGE = 3;

	/**
	 * The feature id for the '<em><b>Configuration Name</b></em>' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int CONFIGURATION_OF_CONFIGURATION_USAGE__CONFIGURATION_NAME = 0;

	/**
	 * The feature id for the '<em><b>Configuration</b></em>' reference.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int CONFIGURATION_OF_CONFIGURATION_USAGE__CONFIGURATION = 1;

	/**
	 * The number of structural features of the '<em>Of Configuration Usage</em>' class.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int CONFIGURATION_OF_CONFIGURATION_USAGE_FEATURE_COUNT = 2;

	/**
	 * The meta object id for the '{@link org.eclipse.xsmp.smp.smdl.configuration.impl.ConfigurationUsageImpl <em>Usage</em>}' class.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @see org.eclipse.xsmp.smp.smdl.configuration.impl.ConfigurationUsageImpl
	 * @see org.eclipse.xsmp.smp.smdl.configuration.impl.ConfigurationPackageImpl#getConfigurationUsage()
	 * @generated
	 */
	int CONFIGURATION_USAGE = 4;

	/**
	 * The feature id for the '<em><b>Configuration</b></em>' containment reference.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int CONFIGURATION_USAGE__CONFIGURATION = 0;

	/**
	 * The feature id for the '<em><b>Path</b></em>' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int CONFIGURATION_USAGE__PATH = 1;

	/**
	 * The number of structural features of the '<em>Usage</em>' class.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int CONFIGURATION_USAGE_FEATURE_COUNT = 2;


	/**
	 * Returns the meta object for class '{@link org.eclipse.xsmp.smp.smdl.configuration.ComponentConfiguration <em>Component Configuration</em>}'.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the meta object for class '<em>Component Configuration</em>'.
	 * @see org.eclipse.xsmp.smp.smdl.configuration.ComponentConfiguration
	 * @generated
	 */
	EClass getComponentConfiguration();

	/**
	 * Returns the meta object for the containment reference list '{@link org.eclipse.xsmp.smp.smdl.configuration.ComponentConfiguration#getInclude <em>Include</em>}'.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the meta object for the containment reference list '<em>Include</em>'.
	 * @see org.eclipse.xsmp.smp.smdl.configuration.ComponentConfiguration#getInclude()
	 * @see #getComponentConfiguration()
	 * @generated
	 */
	EReference getComponentConfiguration_Include();

	/**
	 * Returns the meta object for the containment reference list '{@link org.eclipse.xsmp.smp.smdl.configuration.ComponentConfiguration#getComponent <em>Component</em>}'.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the meta object for the containment reference list '<em>Component</em>'.
	 * @see org.eclipse.xsmp.smp.smdl.configuration.ComponentConfiguration#getComponent()
	 * @see #getComponentConfiguration()
	 * @generated
	 */
	EReference getComponentConfiguration_Component();

	/**
	 * Returns the meta object for the containment reference list '{@link org.eclipse.xsmp.smp.smdl.configuration.ComponentConfiguration#getFieldValue <em>Field Value</em>}'.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the meta object for the containment reference list '<em>Field Value</em>'.
	 * @see org.eclipse.xsmp.smp.smdl.configuration.ComponentConfiguration#getFieldValue()
	 * @see #getComponentConfiguration()
	 * @generated
	 */
	EReference getComponentConfiguration_FieldValue();

	/**
	 * Returns the meta object for the attribute '{@link org.eclipse.xsmp.smp.smdl.configuration.ComponentConfiguration#getPath <em>Path</em>}'.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the meta object for the attribute '<em>Path</em>'.
	 * @see org.eclipse.xsmp.smp.smdl.configuration.ComponentConfiguration#getPath()
	 * @see #getComponentConfiguration()
	 * @generated
	 */
	EAttribute getComponentConfiguration_Path();

	/**
	 * Returns the meta object for class '{@link org.eclipse.xsmp.smp.smdl.configuration.Configuration <em>Configuration</em>}'.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the meta object for class '<em>Configuration</em>'.
	 * @see org.eclipse.xsmp.smp.smdl.configuration.Configuration
	 * @generated
	 */
	EClass getConfiguration();

	/**
	 * Returns the meta object for the containment reference list '{@link org.eclipse.xsmp.smp.smdl.configuration.Configuration#getInclude <em>Include</em>}'.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the meta object for the containment reference list '<em>Include</em>'.
	 * @see org.eclipse.xsmp.smp.smdl.configuration.Configuration#getInclude()
	 * @see #getConfiguration()
	 * @generated
	 */
	EReference getConfiguration_Include();

	/**
	 * Returns the meta object for the containment reference list '{@link org.eclipse.xsmp.smp.smdl.configuration.Configuration#getComponent <em>Component</em>}'.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the meta object for the containment reference list '<em>Component</em>'.
	 * @see org.eclipse.xsmp.smp.smdl.configuration.Configuration#getComponent()
	 * @see #getConfiguration()
	 * @generated
	 */
	EReference getConfiguration_Component();

	/**
	 * Returns the meta object for class '{@link org.eclipse.xsmp.smp.smdl.configuration.ConfigurationDocumentRoot <em>Document Root</em>}'.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the meta object for class '<em>Document Root</em>'.
	 * @see org.eclipse.xsmp.smp.smdl.configuration.ConfigurationDocumentRoot
	 * @generated
	 */
	EClass getConfigurationDocumentRoot();

	/**
	 * Returns the meta object for the attribute list '{@link org.eclipse.xsmp.smp.smdl.configuration.ConfigurationDocumentRoot#getMixed <em>Mixed</em>}'.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the meta object for the attribute list '<em>Mixed</em>'.
	 * @see org.eclipse.xsmp.smp.smdl.configuration.ConfigurationDocumentRoot#getMixed()
	 * @see #getConfigurationDocumentRoot()
	 * @generated
	 */
	EAttribute getConfigurationDocumentRoot_Mixed();

	/**
	 * Returns the meta object for the map '{@link org.eclipse.xsmp.smp.smdl.configuration.ConfigurationDocumentRoot#getXMLNSPrefixMap <em>XMLNS Prefix Map</em>}'.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the meta object for the map '<em>XMLNS Prefix Map</em>'.
	 * @see org.eclipse.xsmp.smp.smdl.configuration.ConfigurationDocumentRoot#getXMLNSPrefixMap()
	 * @see #getConfigurationDocumentRoot()
	 * @generated
	 */
	EReference getConfigurationDocumentRoot_XMLNSPrefixMap();

	/**
	 * Returns the meta object for the map '{@link org.eclipse.xsmp.smp.smdl.configuration.ConfigurationDocumentRoot#getXSISchemaLocation <em>XSI Schema Location</em>}'.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the meta object for the map '<em>XSI Schema Location</em>'.
	 * @see org.eclipse.xsmp.smp.smdl.configuration.ConfigurationDocumentRoot#getXSISchemaLocation()
	 * @see #getConfigurationDocumentRoot()
	 * @generated
	 */
	EReference getConfigurationDocumentRoot_XSISchemaLocation();

	/**
	 * Returns the meta object for the containment reference '{@link org.eclipse.xsmp.smp.smdl.configuration.ConfigurationDocumentRoot#getConfiguration <em>Configuration</em>}'.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the meta object for the containment reference '<em>Configuration</em>'.
	 * @see org.eclipse.xsmp.smp.smdl.configuration.ConfigurationDocumentRoot#getConfiguration()
	 * @see #getConfigurationDocumentRoot()
	 * @generated
	 */
	EReference getConfigurationDocumentRoot_Configuration();

	/**
	 * Returns the meta object for class '{@link org.eclipse.xsmp.smp.smdl.configuration.ConfigurationOfConfigurationUsage <em>Of Configuration Usage</em>}'.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the meta object for class '<em>Of Configuration Usage</em>'.
	 * @see org.eclipse.xsmp.smp.smdl.configuration.ConfigurationOfConfigurationUsage
	 * @generated
	 */
	EClass getConfigurationOfConfigurationUsage();

	/**
	 * Returns the meta object for the attribute '{@link org.eclipse.xsmp.smp.smdl.configuration.ConfigurationOfConfigurationUsage#getConfigurationName <em>Configuration Name</em>}'.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the meta object for the attribute '<em>Configuration Name</em>'.
	 * @see org.eclipse.xsmp.smp.smdl.configuration.ConfigurationOfConfigurationUsage#getConfigurationName()
	 * @see #getConfigurationOfConfigurationUsage()
	 * @generated
	 */
	EAttribute getConfigurationOfConfigurationUsage_ConfigurationName();

	/**
	 * Returns the meta object for the reference '{@link org.eclipse.xsmp.smp.smdl.configuration.ConfigurationOfConfigurationUsage#getConfiguration <em>Configuration</em>}'.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the meta object for the reference '<em>Configuration</em>'.
	 * @see org.eclipse.xsmp.smp.smdl.configuration.ConfigurationOfConfigurationUsage#getConfiguration()
	 * @see #getConfigurationOfConfigurationUsage()
	 * @generated
	 */
	EReference getConfigurationOfConfigurationUsage_Configuration();

	/**
	 * Returns the meta object for class '{@link org.eclipse.xsmp.smp.smdl.configuration.ConfigurationUsage <em>Usage</em>}'.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the meta object for class '<em>Usage</em>'.
	 * @see org.eclipse.xsmp.smp.smdl.configuration.ConfigurationUsage
	 * @generated
	 */
	EClass getConfigurationUsage();

	/**
	 * Returns the meta object for the containment reference '{@link org.eclipse.xsmp.smp.smdl.configuration.ConfigurationUsage#getConfiguration <em>Configuration</em>}'.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the meta object for the containment reference '<em>Configuration</em>'.
	 * @see org.eclipse.xsmp.smp.smdl.configuration.ConfigurationUsage#getConfiguration()
	 * @see #getConfigurationUsage()
	 * @generated
	 */
	EReference getConfigurationUsage_Configuration();

	/**
	 * Returns the meta object for the attribute '{@link org.eclipse.xsmp.smp.smdl.configuration.ConfigurationUsage#getPath <em>Path</em>}'.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the meta object for the attribute '<em>Path</em>'.
	 * @see org.eclipse.xsmp.smp.smdl.configuration.ConfigurationUsage#getPath()
	 * @see #getConfigurationUsage()
	 * @generated
	 */
	EAttribute getConfigurationUsage_Path();

	/**
	 * Returns the factory that creates the instances of the model.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the factory that creates the instances of the model.
	 * @generated
	 */
	ConfigurationFactory getConfigurationFactory();

	/**
	 * <!-- begin-user-doc -->
	 * Defines literals for the meta objects that represent
	 * <ul>
	 *   <li>each class,</li>
	 *   <li>each feature of each class,</li>
	 *   <li>each enum,</li>
	 *   <li>and each data type</li>
	 * </ul>
	 * <!-- end-user-doc -->
	 * @generated
	 */
	interface Literals
	{
		/**
		 * The meta object literal for the '{@link org.eclipse.xsmp.smp.smdl.configuration.impl.ComponentConfigurationImpl <em>Component Configuration</em>}' class.
		 * <!-- begin-user-doc -->
		 * <!-- end-user-doc -->
		 * @see org.eclipse.xsmp.smp.smdl.configuration.impl.ComponentConfigurationImpl
		 * @see org.eclipse.xsmp.smp.smdl.configuration.impl.ConfigurationPackageImpl#getComponentConfiguration()
		 * @generated
		 */
		EClass COMPONENT_CONFIGURATION = eINSTANCE.getComponentConfiguration();

		/**
		 * The meta object literal for the '<em><b>Include</b></em>' containment reference list feature.
		 * <!-- begin-user-doc -->
		 * <!-- end-user-doc -->
		 * @generated
		 */
		EReference COMPONENT_CONFIGURATION__INCLUDE = eINSTANCE.getComponentConfiguration_Include();

		/**
		 * The meta object literal for the '<em><b>Component</b></em>' containment reference list feature.
		 * <!-- begin-user-doc -->
		 * <!-- end-user-doc -->
		 * @generated
		 */
		EReference COMPONENT_CONFIGURATION__COMPONENT = eINSTANCE.getComponentConfiguration_Component();

		/**
		 * The meta object literal for the '<em><b>Field Value</b></em>' containment reference list feature.
		 * <!-- begin-user-doc -->
		 * <!-- end-user-doc -->
		 * @generated
		 */
		EReference COMPONENT_CONFIGURATION__FIELD_VALUE = eINSTANCE.getComponentConfiguration_FieldValue();

		/**
		 * The meta object literal for the '<em><b>Path</b></em>' attribute feature.
		 * <!-- begin-user-doc -->
		 * <!-- end-user-doc -->
		 * @generated
		 */
		EAttribute COMPONENT_CONFIGURATION__PATH = eINSTANCE.getComponentConfiguration_Path();

		/**
		 * The meta object literal for the '{@link org.eclipse.xsmp.smp.smdl.configuration.impl.ConfigurationImpl <em>Configuration</em>}' class.
		 * <!-- begin-user-doc -->
		 * <!-- end-user-doc -->
		 * @see org.eclipse.xsmp.smp.smdl.configuration.impl.ConfigurationImpl
		 * @see org.eclipse.xsmp.smp.smdl.configuration.impl.ConfigurationPackageImpl#getConfiguration()
		 * @generated
		 */
		EClass CONFIGURATION = eINSTANCE.getConfiguration();

		/**
		 * The meta object literal for the '<em><b>Include</b></em>' containment reference list feature.
		 * <!-- begin-user-doc -->
		 * <!-- end-user-doc -->
		 * @generated
		 */
		EReference CONFIGURATION__INCLUDE = eINSTANCE.getConfiguration_Include();

		/**
		 * The meta object literal for the '<em><b>Component</b></em>' containment reference list feature.
		 * <!-- begin-user-doc -->
		 * <!-- end-user-doc -->
		 * @generated
		 */
		EReference CONFIGURATION__COMPONENT = eINSTANCE.getConfiguration_Component();

		/**
		 * The meta object literal for the '{@link org.eclipse.xsmp.smp.smdl.configuration.impl.ConfigurationDocumentRootImpl <em>Document Root</em>}' class.
		 * <!-- begin-user-doc -->
		 * <!-- end-user-doc -->
		 * @see org.eclipse.xsmp.smp.smdl.configuration.impl.ConfigurationDocumentRootImpl
		 * @see org.eclipse.xsmp.smp.smdl.configuration.impl.ConfigurationPackageImpl#getConfigurationDocumentRoot()
		 * @generated
		 */
		EClass CONFIGURATION_DOCUMENT_ROOT = eINSTANCE.getConfigurationDocumentRoot();

		/**
		 * The meta object literal for the '<em><b>Mixed</b></em>' attribute list feature.
		 * <!-- begin-user-doc -->
		 * <!-- end-user-doc -->
		 * @generated
		 */
		EAttribute CONFIGURATION_DOCUMENT_ROOT__MIXED = eINSTANCE.getConfigurationDocumentRoot_Mixed();

		/**
		 * The meta object literal for the '<em><b>XMLNS Prefix Map</b></em>' map feature.
		 * <!-- begin-user-doc -->
		 * <!-- end-user-doc -->
		 * @generated
		 */
		EReference CONFIGURATION_DOCUMENT_ROOT__XMLNS_PREFIX_MAP = eINSTANCE.getConfigurationDocumentRoot_XMLNSPrefixMap();

		/**
		 * The meta object literal for the '<em><b>XSI Schema Location</b></em>' map feature.
		 * <!-- begin-user-doc -->
		 * <!-- end-user-doc -->
		 * @generated
		 */
		EReference CONFIGURATION_DOCUMENT_ROOT__XSI_SCHEMA_LOCATION = eINSTANCE.getConfigurationDocumentRoot_XSISchemaLocation();

		/**
		 * The meta object literal for the '<em><b>Configuration</b></em>' containment reference feature.
		 * <!-- begin-user-doc -->
		 * <!-- end-user-doc -->
		 * @generated
		 */
		EReference CONFIGURATION_DOCUMENT_ROOT__CONFIGURATION = eINSTANCE.getConfigurationDocumentRoot_Configuration();

		/**
		 * The meta object literal for the '{@link org.eclipse.xsmp.smp.smdl.configuration.impl.ConfigurationOfConfigurationUsageImpl <em>Of Configuration Usage</em>}' class.
		 * <!-- begin-user-doc -->
		 * <!-- end-user-doc -->
		 * @see org.eclipse.xsmp.smp.smdl.configuration.impl.ConfigurationOfConfigurationUsageImpl
		 * @see org.eclipse.xsmp.smp.smdl.configuration.impl.ConfigurationPackageImpl#getConfigurationOfConfigurationUsage()
		 * @generated
		 */
		EClass CONFIGURATION_OF_CONFIGURATION_USAGE = eINSTANCE.getConfigurationOfConfigurationUsage();

		/**
		 * The meta object literal for the '<em><b>Configuration Name</b></em>' attribute feature.
		 * <!-- begin-user-doc -->
		 * <!-- end-user-doc -->
		 * @generated
		 */
		EAttribute CONFIGURATION_OF_CONFIGURATION_USAGE__CONFIGURATION_NAME = eINSTANCE.getConfigurationOfConfigurationUsage_ConfigurationName();

		/**
		 * The meta object literal for the '<em><b>Configuration</b></em>' reference feature.
		 * <!-- begin-user-doc -->
		 * <!-- end-user-doc -->
		 * @generated
		 */
		EReference CONFIGURATION_OF_CONFIGURATION_USAGE__CONFIGURATION = eINSTANCE.getConfigurationOfConfigurationUsage_Configuration();

		/**
		 * The meta object literal for the '{@link org.eclipse.xsmp.smp.smdl.configuration.impl.ConfigurationUsageImpl <em>Usage</em>}' class.
		 * <!-- begin-user-doc -->
		 * <!-- end-user-doc -->
		 * @see org.eclipse.xsmp.smp.smdl.configuration.impl.ConfigurationUsageImpl
		 * @see org.eclipse.xsmp.smp.smdl.configuration.impl.ConfigurationPackageImpl#getConfigurationUsage()
		 * @generated
		 */
		EClass CONFIGURATION_USAGE = eINSTANCE.getConfigurationUsage();

		/**
		 * The meta object literal for the '<em><b>Configuration</b></em>' containment reference feature.
		 * <!-- begin-user-doc -->
		 * <!-- end-user-doc -->
		 * @generated
		 */
		EReference CONFIGURATION_USAGE__CONFIGURATION = eINSTANCE.getConfigurationUsage_Configuration();

		/**
		 * The meta object literal for the '<em><b>Path</b></em>' attribute feature.
		 * <!-- begin-user-doc -->
		 * <!-- end-user-doc -->
		 * @generated
		 */
		EAttribute CONFIGURATION_USAGE__PATH = eINSTANCE.getConfigurationUsage_Path();

	}

} //ConfigurationPackage
